// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ1gnn17MvjInYdesQ_wMipxQG1nq5sys',
    appId: '1:89005715065:ios:61b04b7275fe1d6958eea8',
    messagingSenderId: '89005715065',
    projectId: 'shamo-e3696',
    storageBucket: 'shamo-e3696.appspot.com',
    iosBundleId: 'com.example.shamoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ1gnn17MvjInYdesQ_wMipxQG1nq5sys',
    appId: '1:89005715065:ios:61b04b7275fe1d6958eea8',
    messagingSenderId: '89005715065',
    projectId: 'shamo-e3696',
    storageBucket: 'shamo-e3696.appspot.com',
    iosBundleId: 'com.example.shamoApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ1gnn17MvjInYdesQ_wMipxQG1nq5sys',
    appId: '1:89005715065:ios:61b04b7275fe1d6958eea8',
    messagingSenderId: '89005715065',
    projectId: 'shamo-e3696',
    storageBucket: 'shamo-e3696.appspot.com',
    iosBundleId: 'com.example.shamoApp',
  );
}
